baseurl = "http://atlcyber.com"
title = "ATLCyber Hunting Lodge"
theme = "nix"
languageCode = "en-us"
#disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "join"
    weight = 0 
    url = "https://communityinviter.com/apps/atlcyberlodge/join-us-in-the-atlcyber-lodge"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "atlcyber"
  TwitterID = "@atlcyber"
  HeaderUsername = "root"
  HeaderHostname = "atlcyber"
  Email = "headmaster@atlcyber.com"
  About = "A cybersecurity meetup group, online and in-person, for Cybersecurity professionals in the Metro-Atlanta area!"
  ProfilePicture = "img/dark_logo.png"
  SlackURL = "https://communityinviter.com/apps/atlcyberlodge/join-us-in-the-atlcyber-lodge"
  GoogleAnalytics= "UA-121647137-1"
